name: "Lambda Kollektiv Blog"

description: "Projects, ideas and opinions"

url: "http://localhost:4000"

paginate: 10

markdown: kramdown

highlighter: pygments

permalink: pretty

github:
    repo: github.com/lambda-kollektiv/lambda-kollektiv.github.io

pages_list:
    archive: '/archive/'
    about: '/about/'
