#+TITLE: lambda-kollektiv
#+CATEGORY: lambda-kollektiv
#+TAGS: blog planning meeting
#+TODO: TODO(t) STARTED(s!) WAITING(w!) | FIXED(f!) DONE(d!) 
#+TODO: CANCELED(c@)
#+STARTUP: overview 
#+STARTUP: hidestars
=================

**** Installation
=Ruby >= 2.0.0= is required as jekyll is used on gh-pages. Check version:

```
ruby --version
```

If not installed:

```
sudo apt-get install ruby
```

Install =bundler= for easier ruby lib management configured in =Gemfile=:
```
sudo gem install bundler
```

Now run the server:

```
bundle exec jekyll server
```

and for drafts run 
```
bundle exec jekyll server --drafts
```
**** TODOs
**** References
**** License

Copyright © 2015 Konrad Kühne & Judith Massa

Distributed under the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
