#+TITLE: lambda-kollektiv
#+CATEGORY: lambda-kollektiv
#+TAGS: blog planning meeting
#+TODO: TODO(t) STARTED(s!) WAITING(w!) | FIXED(f!) DONE(d!) 
#+TODO: CANCELED(c@)
#+STARTUP: overview 
#+STARTUP: hidestars

**** Installation
Mimimum =Ruby 2.0.0= is required as jekyll is used on gh-pages. Check version:

#+BEGIN_SRC 
ruby --version
#+END_SRC

If not installed:

#+BEGIN_SRC 
sudo apt-get install ruby
#+END_SRC

Install =bundler= for easier ruby lib management configured in =Gemfile=:

#+BEGIN_SRC 
sudo gem install bundler
#+END_SRC

Now run the server:

#+BEGIN_SRC 
bundle exec jekyll server
#+END_SRC

and for drafts run 
#+BEGIN_SRC 
bundle exec jekyll server --drafts
#+END_SRC

**** TODOs
***** TODO deploy gitlab					 :deployment:
     DEADLINE: <2015-08-06 Do>
     :PROPERTIES:
     :Created: [2015-07-21 Di 19:00]
     :Assigned_to: kordano
     :END:
    
- See [[https://about.gitlab.com/features/]] for details 
***** TODO design company logo 					     :design:
    DEADLINE: <2015-07-22 Mi>
    :PROPERTIES:
    :Created: [2015-07-13 Mo 15:48]
    :Assigned_to: kordano
    :END:
**** References
**** License

Copyright © 2015 Konrad Kühne & Judith Massa

Distributed under the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
